### ISSUE TITLE
Remove docs callout when YAML template process is resolved

### ISSUE THREAD

**Issue by rhoads-zach** [fabric8-launcher/launcher-documentation#169]
http://appdev.openshift.io/minishift-installation.html#_create_the_launchpad_application_manually

**Comment by tradej** [comment]
This seems to still be hanging on the developers getting the Launcher as an option in Minishift.

For current progress, see openshiftio/launchpad-templates#2.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-299
