### ISSUE TITLE
Use modular templates from the Modular Docs Initiative

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#318]
As I can see, our doc set—albeit modularised—does not follow the [Modular Docs Initiative guidelines](https://url.corp.redhat.com/891ce40) (Internal link) on how to author modular content, especially the templates, and having one module as a self-contained piece of information that makes sense on its own (as an example of a file that is not that, see `$REPO_HOME/docs/topics/health-check-mission-basic-interaction-spring-boot-tomcat.adoc`). I suggest sticking to the templates when authoring new content, and devising a plan for consolidating existing content so that it follows the templates. WDYT?

**Comment by rhoads-zach** [comment]
between current state of docs and this:
https://issues.jboss.org/browse/RHOARDOC-42

I believe this issue can be closed.

We can open a new JIRA to track additional work for this if needed @tradej
