### ISSUE TITLE
Write missing chapters in the Contribution Guide

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#377]
Currently missing chapters:

* Metadata and Attributes
* Requirements (naming, supportability statements, legal requirements etc.)
* Internal JIRA issues workflow
* ~~Publishing~~

Follows up on #376, resolves #239.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-507
