### ISSUE TITLE
Establish conventions when writing AsciiDoc

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#416]
Sub-tasks:
* Use the result of the CCS-wide Asciidoctor Markup Conventions initiative
* Sync with other products in specialised areas like naming etc. (OpenShift)

**Comment by inoxx03** [comment]
+1

**Comment by cmoulliard** [comment]
> CCS-wide Asciidoctor Markup Conventions initiative

Is there a link to read what this initiative proposes ?

**Comment by tradej** [comment]
@cmoulliard The results are not available yet, but should be in the matter of days, a few weeks at most.

**Comment by tradej** [comment]
Update: The final document is not yet finished. I have requested acceleration of the matter.

**Comment by inoxx03** [comment]
@tradej @cmoulliard FYI: The Red Hat [AsciiDoc Markup Conventions](https://redhat-documentation.github.io/asciidoc-markup-conventions/) have been published on GitHub Pages.
I'm fairly certain the the linked doc is the latest revision to date (but I don't know if this is the final document).

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-546
