### ISSUE TITLE
Running integration tests, documenting expected output

### ISSUE THREAD

**Issue by rdruss** [fabric8-launcher/launcher-documentation#582]
In the Eclipse Vert.x Runtime Guide, section 2.2.5 discusses how to run the integration tests that are distributed with the ConfigMap booster.  When the tests are run, they complete with 0 Failures and 0 Errors.  However, the output from running the tests has a io.fabric8.kubernetes.client.KubernetesClientException that generates a stacktrace as well as a message that states, "Error deleting resource DeploymentConfig configmap-vertx retrying #1".  Should there be a discussion that these are expected results and why to prevent confusion from the user?

**Comment by cescoffier** [comment]
The exception is thrown when an entity created by the tests cannot be deleted (generally because it has already been deleted). This is an issue in the OpenShiftTestAssistant - we could catch the exception and reduce the impact on the screen (just logging a "short" message)

**Comment by Ladicek** [comment]
Yea, there's a retry loop in OpenShiftTestAssistant, and in that retry loop, if an error occurs, we do `e.printStackTrace();` and then print a short error message before retrying. The `e.printStackTrace();` should IMHO be removed.

**Comment by rhoads-zach** [comment]
@rdruss @cescoffier @Ladicek do you think its appropriate for us to include a note in the docs about this? or do you think it needs to get fixed in OpenShiftTestAssistant?

**Comment by Ladicek** [comment]
I believe we should fix OpenShiftTestAssistant, but it seems to me that noone wants to hear about changing OpenShiftTestAssistant anymore. I won't speculate about the reasons. If you could mention in the docs that a stacktrace followed by a message about retrying is harmless, that would be great. It would surely be faster than propagating an OpenShiftTestAssistant change to all boosters.

Please just note that this isn't specific to Vert.x ConfigMap, this can happen in all booster tests (except Node.js obviously :-) ).

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-712
