### ISSUE TITLE
Deduplicate cico_build_deploy.sh and cico_build_test.sh

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#585]
Due to #504, there is a new script called `cico_build_test.sh` in the repo root. This script is partially identical to `cico_build_deploy`, so it warrants refactoring to eliminate the code duplication.

**Comment by tradej** [comment]
This is soft-blocked by #609 because conflicts are more than likely to happen.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-715
