### ISSUE TITLE
Assign hardcoded IDs to all headings

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#663]
Follow-up to #647.

All headings should have consistent, hard-coded IDs so that a change in the heading's wording does not affect existing links.

**Comment by tradej** [comment]
Dependent on redhat-documentation/modular-docs/pull/19.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-793
