### ISSUE TITLE
Reword + improve complicated passages

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#670]
Some parts of the docs, especially the introductions, are often quite verbose and hard to read, especially for newcomers to the topic. I believe we should reword these parts for improved readablility, among others:

* _General Missions intro:_ Very technical terms, long sentences that are hard to read.
* _REST API mission intro:_ Quite technical. Given it's the most basic of the missions, I believe it should be written in the most basic way.
* _Circuit Breaker intro sections:_ Long sentences that are hard to read.
* _WildFly Runtime details:_ Quite technical and some formulations are fairly vague, e. g. "just-enough-appserver".
* _Using a Nexus Repository Server With the launch.openshift.io Application on a Single-node OpenShift Cluster:_ Long sentences that are hard to read.

This is a follow-up issue to #309.

**Comment by inoxx03** [comment]
I own some of the docs sections that you've referenced in the description (Circuit Breaker, Nexus) as having clumsy wording. I'll take this issue.

**Comment by tradej** [comment]
No problem, just please don't close the issue until we've agreed the docs are in a reasonably good shape in terms of readability—the list of passages in the description is non-exhaustive.

**Comment by inoxx03** [comment]
Understood. I'll do a partial resolution and keep the issue open as long as there are fixes left to be made. Thanks for the heads up:)

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-800
