### ISSUE TITLE
Consistent capitalisation of RHOAR concepts

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#673]
In the majority of contexts, we use _booster, mission,_ or _runtime_ lowercased. However, there are portions of the docs where they are uppercased, namely _boosters_ are referred to as _Boosters_ in the CRUD mission description.

I believe we need to lowercase all the occurrences of such terms (except for headings and so, of course) to maintain consistency.

**Comment by Ladicek** [comment]
+1 from me

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-803
