### ISSUE TITLE
HTML previews for pull requests

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#676]
In other teams, a build service is used to preview the docs in the HTML form. In my opinion, we should have a similar service available to facilitate SME and peer reviews. In the experience of me and my colleagues, having the rendered document readily available helps getting feedback greatly, especially from third parties.

 The solution could be run in [ci.centos.org](https://ci.centos.org), or could use some file hosting functionality, e. g. [pages.github.io](https://pages.github.io). The build and uploading of the docs should be fully automated.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-806
