### ISSUE TITLE
Minor edits for Spring Boot guide and related missions

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#680]
1..Section 3 Relational Database  Backend Mission - Spring Boot Tomcat Booster
minor grammar changes
 correction for sentence below -> integration tests (its repeated in another place in this doc)
This booster also contains a set of automated integration test that can be used to verify that the application is fully integrated with the database.

2. In these sections potentially remove the word still from sentence below or use different grammar
2.1.1.1.1 Deploying Using launch.openshift.io
2.2.3.1.2. Deploying Using the oc CLI Client
You must still create a booster ...  remove the word still or re-word the sentence

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-810
