### ISSUE TITLE
Add documentation for running integration tests to all booster guides

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launcher/launcher-documentation#734]
Looking at https://appdev.prod-preview.openshift.io/docs/ and ignoring the Secured booster (for which we have #721), I see that:

- The Spring Boot guide has a chapter on running integration tests for all boosters.
- The Vert.x guide has a chapter on running integration tests for all boosters except REST API Level 0.
- The WildFly Swarm guide has a chapter on running integration tests only for CRUD and Circuit Breaker boosters.

This doesn't sound intentional, and maybe it's just because some parts were left commented out by accident.

**Comment by inoxx03** [comment]
@Ladicek Would you propose including integration test sections for all the missions? IIRC, we've never had them for some of the missions, but adding them now will not be a problem.

**Comment by Ladicek** [comment]
I'm proposing consistency across all runtimes :-) Spring Boot has a section for integration tests for _all_ missions, Vert.x for almost all, Swarm only for 2 of them. That's weird.

**Comment by inoxx03** [comment]
@Ladicek I agree. Let's add integration test sections for all missions/boosters, then.

**Comment by inoxx03** [comment]
Also, it might be practical to put the integration test sections into separate topics (which is currently only done for the CRUD mission).

**Comment by inoxx03** [comment]
@Ladicek Does running integration tests in an OpenShift project that already contains the booster application remove the application once the test is finished? If it does I'll inlcude a callout  about it in the docs.

**Comment by Ladicek** [comment]
Good question. I didn't verify the behavior in such situation. Let me check.

**Comment by Ladicek** [comment]
... and the answer is YES, if the application is already deployed before running the test, it will be gone when the test finishes.

**Comment by tradej** [comment]
I will address the WildFly Swarm integration tests with the dev team in a meeting today.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-864
