### ISSUE TITLE
Consolidate module naming, headers, and anchors

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#737]
All modules should be named as follows:

`$MODULETYPE_$MODULETITLE.adoc`

where `$MODULETYPE` is one of `con`, `proc`, or `assembly`, and `$MODULETITLE` is the verbatim title of the module, all in lowercase, with dashes instead of whitespace and special characters.

All anchors should be in the format:

`[#$MODULETITLE]` or `[#$MODULETITLE_{context}]`

where $MODULETITLE is the verbatim title of the module, all in lowercase, with dashes instead of whitespace and special characters.

All `include` and `xref` directives need to be updated accordingly.

For more information, see the [Modular Documentation Reference Guide](https://htmlpreview.github.io/?https://github.com/redhat-documentation/modular-docs/blob/master/modular-docs-manual/modular-docs-manual.html).

Partially resolves #318.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-867
