### ISSUE TITLE
Spring Boot:  Include information in the guide  that  answers why a customer chooses spring boot

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#745]
NOTE** Not in scope for current milestone: Information for Use-case on Spring Boot (greenfield development)
a) emphasis on benefits of Spring Boot on OpenShift (Java and other specific components to call out here??)
>> Added a more technical intro to position Spring Boot and Web, Web Development doc (see Google Doc) 
b) contrast with Competitors Spring Boot
>> I will ask to John if he agrees 
Tracked in [OBST-459](https://issues.jboss.org/browse/OBST-459).

**Comment by rhoads-zach** [comment]
moved to JIRA: https://issues.jboss.org/browse/RHOARDOC-48
