### ISSUE TITLE
Spring Boot: Include architecture level information  (need a diagram)  

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#746]
NOTE** Not in scope for current milestone:  Include architecture level information for Spring boot (need a diagram)  >

>> No diagram has been added but a table of the features. We could perhaps add such picture ->  https://www.dropbox.com/s/fazikxr2l25gkdc/Screenshot%202017-10-25%2017.31.10.png?dl=0
Tracked in [OBST-460](https://issues.jboss.org/browse/OBST-460).

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-53
