### ISSUE TITLE
Replace different deployment (OSL, OSO, OCP) parametres and names with OpenShift where applicable

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#759]
In some modules, it may be possible to replace the the `{OpenShiftLocal}` or `{OpenShiftContainerPlatform}` occurrences with simple "OpenShift". When doing that, it may happen the `:parameter-deployment:` becomes unnecessary. Remove it then along with those attributes.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-889
