### ISSUE TITLE
It would make sense to explain ConfigMap before describing the mission

### ISSUE THREAD

**Issue by metacosm** [fabric8-launcher/launcher-documentation#775]
i.e. move About ConfigMap section from configmap-mission-intro to configmap-mission-intro-paragraph?

**Comment by lavernw1** [comment]
@metacosm The summary of the  mission intro comes first to let the  reader know  what  to expect in this chapter. The we dissuss what a configmap is.  Thats the reason  the content is presented in this order.

**Comment by metacosm** [comment]
@lavernw1 It feels weird to me to present a mission using concepts that have yet to be introduced…

**Comment by rhoads-zach** [comment]
@lavernw1 based on the label, i'm assuming this is resolved, can you provide the link to the PR where this is fixed?
