### ISSUE TITLE
We should use the same wording in the doc as in launcher

### ISSUE THREAD

**Issue by metacosm** [fabric8-launcher/launcher-documentation#777]
The doc only speaks of ConfigMap mission, while Launcher uses Externalized Configuration. While the confusion is minimal, there should ideally be none. :)

**Comment by lavernw1** [comment]
@metacosm @rhoads-zach
This is a WIP.  ConfigMap mission intro paragraph was streamlined as part of modular docs fixes.  
These changes minor typo fix. Considered changing interaction section text for "configmap configuration"  to externalized configuration, but left it as is .

**Comment by metacosm** [comment]
The issue here is that there is a discrepancy between launcher and doc wording. Launcher calls this mission "Externalized configuration" (which I think makes more sense) while the doc calls it "ConfigMap". Both should be in sync. While it might be easier to change the launcher wording, I really think this mission should be called Externalized configuration (embodies the goal) as opposed to ConfigMap (how it's implemented).

**Comment by lavernw1** [comment]
@metacosm thanks for providing the update.  If theres consensus on changing mission  name we can consider that an enhancement.

**Comment by Ladicek** [comment]
I agree with @metacosm's suggestion and reasoning.

**Comment by lavernw1** [comment]
@Ladicek thanks. We've gotten other feedback regarding changing the mission name and I'm implementing it via this WIP issue.

**Comment by rhoads-zach** [comment]
resolved in linked PRs
