### ISSUE TITLE
WIP DO NOT MERGE: Improvement: Add link to OpenShift S2I Build process doc

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-documentation#779]
The Spring Boot CRUD booster mentions S2i process without proposing a link where the end user can discover what is S2I process means

![screenshot 2017-11-06 15 57 46](https://user-images.githubusercontent.com/463790/32447157-81bfe3b4-c30b-11e7-98c1-708da98e6b8b.png)

Remark : This remark is general and not specific to this runtime or mission

**Comment by lavernw1** [comment]
Closing this issue. Fix implemented and PR is closed. https://github.com/fabric8-launcher/launcher-documentation/pull/916
