### ISSUE TITLE
Improvement: Use a generic pod name convention

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-documentation#780]
The doc refers in some place the name of the pod to check/control if the status is running

![screenshot 2017-11-06 16 00 37](https://user-images.githubusercontent.com/463790/32447231-c1c988f2-c30b-11e7-9493-ba2d9c210ac0.png)

We should adopt a more generic convention name instead of using a pod name created during a demo. 

E.g. 

- PostgreSQL : `my-database-1-aaaa -> <MY-DATABASE-1>-<UID>` where `<UID>` is a unique identifier generated by the Kubernetes API during the pod creation
- `My application : MY_APP_NAME-1-aaaaa`, `Spring Boot CRUD : spring-boot-rest-http-crud-1-pqx17` -> `<BOOSTER-NAME-1>-<UID>`

**Comment by rhoads-zach** [comment]
Moved to Jira: https://issues.jboss.org/browse/RHOARDOC-17
