### ISSUE TITLE
ConfigMap mission: set up using oc cli should be simplified

### ISSUE THREAD

**Issue by metacosm** [fabric8-launcher/launcher-documentation#786]
Instead of using a sequence of commands, we could just do:
`oc create -f .openshiftio/resource.configmap.yaml`

**Comment by rhoads-zach** [comment]
This is a feature enhancement that we'll move to low for now.

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-21
