### ISSUE TITLE
Fix the table in chapter 2.1.2. Configuration

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#822]
The table in WFS chapter 2.1.2. Configuration has too many columns. It should be reworked into a list, for example like the list of system properties in the [BPM Suite Administration and Configuration Guide](https://access.qa.redhat.com/documentation/en-us/red_hat_jboss_bpm_suite/6.4/single/administration_and_configuration_guide/#list_of_system_properties).

**The change must be first committed to the upstream WFS repository and then synced to this one.**

**Comment by tradej** [comment]
Upstream work is done, waiting for sync to WFS prod repo.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-952
