### ISSUE TITLE
Refactor the "Breakdown of POM Components" chapter

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#858]
This is a follow-up issue to #761, #824, and #855.

Investigate and implement the best way of reintroducing the information to the guides.

Suggestions:
* Document snippets of the POM file with non-obvious configuration bits for each mission on each runtime. Put the information into the relevant booster's chapter.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-988
