### ISSUE TITLE
Spring Boot:  Document workflow for project packaged as a WAR file 

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#862]
Add example workflow for using a Spring Boot  project packaged as a WAR and which contains JSP pages and JSP Tage Library(JSTL). See [SB-171](https://github.com/fabric8-launch/appdev-documentation/issues/862).

**Comment by lavernw1** [comment]
Updated to link the related JIRA.

**Comment by inoxx03** [comment]
content in PR: #958

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-66
