### ISSUE TITLE
Ability to turn off validation on demand

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#866]
In case there is a validation bug (such as #864), it should be possible to easily disable validation. Needs to be described in the Contrib Guide.

Suggestion:
* Check for a `$REPO_HOME/.validation-ignore` file. If found, all scripts shall immediately `return 0` and pass.

This issue is low priority as we don't need passing tests to accept PRs.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-996
