### ISSUE TITLE
Consider removal of upstream docs links

### ISSUE THREAD

**Issue by tradej** [fabric8-launcher/launcher-documentation#881]
The links to the _HowTo, Reference,_ and _User Guides_ in the [Additional Resources](https://github.com/fabric8-launch/appdev-documentation/blob/master/docs/topics/wf-swarm-dev-guide-additional-resources.adoc) section of the WFS guide may not be useful since most of the relevant content is included in this repository (in the `docs/topics/wildfly-swarm` directory; the instructions for syncing are in the [Contribution Guide](https://appdev.openshift.io/docs/contrib-guide.html#syncing-with-wildfly-swarm-docs)). Consider removing the links.

This is a follow-up issue to #873.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1011
