### ISSUE TITLE
describe what to do if an S2I source build produces multiple .JARs

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launcher/launcher-documentation#900]
The Java S2I image we use by default copies `*.jar` from Maven output `target/` directory to `/deployments` in the resulting image. Next, when a container starts from that image, the `run-java.sh` script tries to find _one_ `.jar` in `/deployments`, and if there's none or if there are more than one, produces an error.

This can easily happen with WildFly Swarm when using `<packaging>jar</packaging>` (as there will be the original `app.jar` and the `app-swarm.jar` uberjar), or with WildFly Swarm using `<packaging>war</packaging>` and configuring the Maven WAR plugin to also produce a `-classes` JAR (as there will be `app.war`, `app-classes.jar` and `app-swarm.jar`), or when using Spring Boot and configuring the Spring Boot Maven plugin to `repackage` the artifact with some classifier (as there will be `app.jar` and `app-classifier.jar`). But it can generally happen whenever Maven produces more than one `.jar` in `target/`.

There are 3 possible solutions that I'm aware of:

- use some Maven plugin (e.g. `maven-antrun-plugin`) to delete the original JARs and only keep the correct single one
- add the `ARTIFACT_COPY_ARGS` environment variable to the OpenShift build config, with a value that selects the correct JAR to copy to `/deployments` (e.g. `*-swarm.jar` with WildFly Swarm)
- add the `JAVA_APP_JAR` environment variable to the OpenShift deployment config, with a value that selects the correct JAR to run (e.g. `app-swarm.jar`, wildcards seem unsupported here)

My favorite is the 2nd option, as that doesn't require modifying the Maven build and allows using wildcards, so if the artifact name changes, this configuration can most likely stay intact.

EDIT: internal reference: https://issues.jboss.org/browse/OBST-55

**Comment by quintesse** [comment]
But we already have Wildfly Swarm projects that successfully use S2I, right? Wouldn't they fail according to what you're describing here?

**Comment by Ladicek** [comment]
No booster is currently failing because of this. All Swarm boosters use a packaging of WAR. In one case, there's the `-classes.jar`, but I used the 2nd solution to fix this.

**Comment by quintesse** [comment]
ok, didn't know that. Thanks for the explanation :)

**Comment by Ladicek** [comment]
In the issue description, I also mention Spring Boot and its Maven plugin `repackage` goal -- I know we configure it in all Spring Boot boosters, but didn't know how we solve the problem. Turns out we also employ the 2nd solution -- the S2I templates configure `ARTIFACT_COPY_ARGS` to `*-exec.jar` (because `exec` is the classifier we use in the Spring Boot boosters).

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1030
