### ISSUE TITLE
Spring Boot: Document how to use HTTP/2, configure or use it

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#902]
Document use of HTTP/2 protocol with Spring Boot. Refer to [CLOUD-2177](https://issues.jboss.org/browse/CLOUD-2177) for a link to a sample procedure to deploy, test and debug the application and use the Apache Tomcat Connector to expose the standard HTTP protocol. See [OBST-540](https://issues.jboss.org/browse/OBST-540)

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-60
