### ISSUE TITLE
Determine expected content for runtime details and introductory sections for guides

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#913]
Determine which concepts and types of information is needed in runtime details and introductory section of guides. Would like to have a common/consistent set of runtime information for each guide, then potentially additional introductory information or chapters specific to each runtime. 

For example, Currently some information provided in runtime details:  version information, cloud concepts,  features and frameworks summary.

**Comment by inoxx03** [comment]
@lavernw1 Thank you for bringing this up.
The current version of the Vert.x Runtime Guide features a brief introduction to high-level concepts related to microservices (e.g. reactive systems architecture, reactive application programming, cloud- and container-native application design, etc.) I gather from several discussions between ENG teams that different runtimes have slightly different approaches to implementing such concepts. Perhaps, in our runtime guide introductions, we could elaborate on these differences by explaining, say, how Vertx and Spring Boot handle asynchronous communication between applications in a system. From a docs point of view, the interesting part would be providing content that would be simultaneously:
* sufficiently informative
* not overwhelmingly technical (although, IMHO, a reasonable level of technical complexity will have to be retained for the content to be of value here:))

**Comment by rhoads-zach** [comment]
Moved here: https://issues.jboss.org/browse/RHOARDOC-1043
