### ISSUE TITLE
Demarcation point between OpenShift and framework

### ISSUE THREAD

**Issue by mocenas** [fabric8-launcher/launcher-documentation#922]
The documentation should somehow describe what does the framework do. Especially what is responsibility of openShift and what is responsibility of framework. Without it, it might be confusing for people whose are not used to these technologies.

**Comment by Ladicek** [comment]
Yea I guess a lot of users will be somewhat familiar with their framework of choice, but will be OpenShift newcomers.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1052
