### ISSUE TITLE
Building app from scratch

### ISSUE THREAD

**Issue by mocenas** [fabric8-launcher/launcher-documentation#923]
The docs does not contain anything about how to build a springboot/vert.x/swarm application from scratch.

**Comment by Ladicek** [comment]
We already had several issues that touched on this topic (#240, #243, #700), but all of them are closed and this content still doesn't exist. (Well maybe it does for Swarm, as we import the Swarm community docs; not sure about others.)

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1053
