### ISSUE TITLE
Relation db login credentials

### ISSUE THREAD

**Issue by mocenas** [fabric8-launcher/launcher-documentation#926]
In springBoot doc 2.3.1 - relational database -> deployment contains command:
oc new-app -e POSTGRESQL_USER=luke -ePOSTGRESQL_PASSWORD=secret -ePOSTGRESQL_DATABASE=my_data openshift/postgresql-92-centos7 --name=my-database

are all the credentials and db name somehow significant? Does a user need to use them somewhere? The docs should answer this.

**Comment by inoxx03** [comment]
@metacosm @cmoulliard When creating a new database application for the relational database on the command line, are the specific values above required? will the booster application work with the database even if different values for `POSTGRESQL_USER` `POSTGRESQL_PASSWORD`, `POSTGRESQL_DATABASE` are used? Can the user opt to use different credentials?

**Comment by Ladicek** [comment]
Yea the specific values are significant, they are used in the configuration of the applications.

- Spring Boot:
    - https://github.com/snowdrop/spring-boot-crud-booster/blob/master/src/main/fabric8/credentials-secret.yml
    - https://github.com/snowdrop/spring-boot-crud-booster/blob/master/src/main/fabric8/deployment.yml#L10-L21
    - https://github.com/snowdrop/spring-boot-crud-booster/blob/master/src/main/resources/application-openshift.properties
- Vert.x:
    - https://github.com/openshiftio-vertx-boosters/vertx-crud-booster/blob/master/src/main/fabric8/credentials-secret.yml
    - https://github.com/openshiftio-vertx-boosters/vertx-crud-booster/blob/master/src/main/fabric8/deployment.yml#L7-L16
    - https://github.com/openshiftio-vertx-boosters/vertx-crud-booster/blob/master/src/main/java/io/openshift/booster/CrudApplication.java#L48-L51
- WildFly Swarm:
    - https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http-crud/blob/master/src/main/fabric8/credentials-secret.yml
    - https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http-crud/blob/master/src/main/fabric8/deployment.yml#L10-L21

**Comment by inoxx03** [comment]
@Ladicek Thank you:) I figured there would probably be reason for having a particular set of credentials, but didn't know where to look:) Thanks for providing context.
I think we could mention in the docs that the booster application is specifically configured to require these credentials.

**Comment by Ladicek** [comment]
Yea I think there should be a note about this. Not sure how detailed that should be.

**Comment by metacosm** [comment]
@Ladicek is a ⭐️

**Comment by inoxx03** [comment]
fixed by PR #984

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1056
