### ISSUE TITLE
ConfigMap booster, step for oc policy add-role-to-user actually needed?

### ISSUE THREAD

**Issue by juangon** [fabric8-launcher/launcher-documentation#939]
While following steps for Wildfly Swarm configmap booster, it throws an error:

> Error from server (NotFound): the server could not find the requested resource

while executing command:

> oc policy add-role-to-user view -n $(oc project -q) -z default

Even after this error, booster behaves normally. Should be this step be removed from README?

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1069
