### ISSUE TITLE
Spring Boot Guide  editing  review comments

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#957]
Incorporate feedback from docs editing review(peer review) for Spring boot guide. This includes comments for  missions common to all runtime guides. This issue is tracked in  [OBST-537](https://issues.jboss.org/browse/OBST-537).

**Comment by rhoads-zach** [comment]
@lavernw1 per label, it seems like this was addressed in a PR, but i can't track it down. Please link to the PR where this was solved.
