### ISSUE TITLE
minimalism feedback: update headings and titles

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#975]
Use shorter titles as appropriate (when not due to modular templates/parameters)
Titles should reflect what the user is doing. 
Tool being used doesn't have to be in the title most of the time.
See [OBST-533](https://issues.jboss.org/browse/OBST-533)

**Comment by lavernw1** [comment]
@rhoads-zach @tradej @inoxx03 @Ladicek  Let me know your thoughts, I'm making these types of  changes for shortening titles in our docs: 
For Example :

Shortening Titles: 
1) Shortening subtitles- In procedures where context is already provided in the main heading, determine if we can remove mission name or Openshift/minishift or  name of tool being used from subtitles or subheadings. Note: we have separate  Minishift and Openshift procedures for some actions.

In procedure 2.2 Building and Deploying the REST API Level 0 Booster to Single-node OpenShift Cluster
shorten the subheading below as follows:
Getting the Fabric8 Launcher Tool URL and Credentials on Single-node OpenShift Cluster -> Getting the Fabric8 Launcher Tool URL and Credentials


2) Simplifying the  title: to match the task the user is performing:
Interacting with the Secured Booster -> Using the Secured Booster 
(Using is a less complex word. We might even want a more specific word like "configuring" or something similar.)
Interacting with the Secured Booster with the Web Client -> Using the Secured Booster with the Web Client

**Comment by Ladicek** [comment]
I think this makes sense, but I can also see how people, who are looking at an `html-single` variant of the docs, can feel lost due to the sheer amount of text duplicity, and overly explicit headings might help with that.

**Comment by lavernw1** [comment]
@Ladicek thanks, for the update. I'm Keeping that in mind for the cases where we have both minshift and OpenShift versions of procedures.

**Comment by tradej** [comment]
In line with what @Ladicek says, I'm all for making the titles less verbose (point 2), but not sure if removing information (point 1) is the way to go. If I am not mistaken, some modules may be included even ~10 times in a book (5 missions × 2 OpenShift deployments), so I would advocate for keeping information in rather than out.

If we do decide to go with drastically less information-dense titles, keep in mind the anchor IDs need to be contextualised properly in order not to break the navigation and builds.

**Comment by lavernw1** [comment]
@tradej thanks.  I dont intend on changing info related to the anchors. I'll touch base on this.

**Comment by lavernw1** [comment]
@tradej the issue is to have better titles, so I wouldn't shorten them unnecessarily. Also good to know about keeping proper context for navigation.

**Comment by inoxx03** [comment]
My $.02:

I would agree with @Ladicek and @tradej on both points here.
1. Some titles notably [Appendix A: Using a Nexus Repository Server With the Fabric8 Launcher Tool on a Single-node OpenShift Cluster
](https://appdev.openshift.io/docs/minishift-installation.html#_using_a_nexus_repository_server_with_the_fabric8_launcher_tool_on_a_single_node_openshift_cluster) definitely need to be made less verbose.

However, the current structure of the booster guides is such that when viewed as `html-single`, the simplified or generic titles would appear many time isn the same document, thus hindering the searchability of the document using CTRL+F in the browser, among other things.

Sheldon is also making an important point about the anchor IDs.
AFAIK, we have heretofore intended to have our titles match the ID anchors to create predictable URLs when linking to specific sections.
I'm not saying that we cannot simplify titles only, leaving ID's more explicit to preserve the URLs, but we must consider this when planning to make the change.

Other than that I'm all for the title simplification:)

**Comment by lavernw1** [comment]
@inoxx03 thanks for your update.  I had a few build issues with IDs. What I was trying was to simplify the title, and keep the IDs explicit (with context) to preserve the URLs.  I'll  reconsider the changes to  ensure the titles and anchors match.

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-125
