### ISSUE TITLE
minimalism feedback:  Rewrite mission proficiencies to have more specific guidelines

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#976]
Missions are currently classified as foundational, advanced, expert etc.
Update the mission definitions to be more descriptive. What kind of prior knowledge does "foundational" really require? OpenShift knowledge?

Note: This information is shared between the runtime guides and the launcher UI. Consider a long form of the definitions for the guides if needed.
See [OBST-533](https://issues.jboss.org/browse/OBST-533)

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-126
