### ISSUE TITLE
minimalism feedback: Update Section 2.6.3 Standing Up Red Hat SSO and Booster Simplification table

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#977]
Update the table and section per minimalism comments. Simplify wording used. Possibly, The section should include what you CAN use in production. (research this). See[ OBST-533](https://issues.jboss.org/browse/OBST-533)

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-127
