### ISSUE TITLE
minimalism feedback: Simplify writing: Use simpler terminology, eliminate warnings and passive voice

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launcher/launcher-documentation#978]
Use simpler wording, avoid using words such as agnostic and opinionated. 
Eliminate passive voice and warnings.  Use fewer warnings or incorporate information in  procedures as prerequisites when appropriate.
Currently have too many warnings which may add confusion for the user or they may be missed entirely.
See [OBST-533](https://issues.jboss.org/browse/OBST-533)

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-124
