### ISSUE TITLE
Remove text - Patch jenkins to use admin as role from bash script

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-documentation#981]
This step is not included anymore with the script and then the text `3) Patch jenkins to use admin as role` should be removed

https://github.com/fabric8-launcher/launcher-documentation/blob/master/scripts/deploy_launcher_mission.sh#L6

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1111
